export const people = [
  {
    firstName: "Michael",
    lastName: "Jordan",
    email: "MJ23@gmail.com",
    phone: "0123456789",
    address: "23 Basketball Court",
    contractType: "Permanent",
    startDate: new Date("2023-11-15"),
    finishDate: new Date("2024-11-30"),
    employmentType: "Full-Time",
    hoursPerWeek: 40.0,
  },
  {
    firstName: "Maria",
    lastName: "Garcia",
    email: "MariaGarcia@gmail.com",
    phone: "0765432109",
    address: "15 Garden Avenue",
    contractType: "Contract",
    startDate: new Date("2023-10-20"),
    finishDate: new Date("2024-05-31"),
    employmentType: "Part-Time",
    hoursPerWeek: 30.0,
  },
  {
    firstName: "Alex",
    lastName: "Wong",
    email: "AlexWong@yahoo.com",
    phone: "0321654987",
    address: "42 Skyline Street",
    contractType: "Permanent",
    startDate: new Date("2023-09-10"),
    finishDate: new Date("2024-09-30"),
    employmentType: "Full-Time",
    hoursPerWeek: 35.0,
  },
  {
    firstName: "Emily",
    lastName: "Chen",
    email: "EmilyChen@gmail.com",
    phone: "0876543210",
    address: "7 Meadow Lane",
    contractType: "Permanent",
    startDate: new Date("2023-08-05"),
    finishDate: new Date("2023-12-31"),
    employmentType: "Full-Time",
    hoursPerWeek: 38.0,
  },
  {
    firstName: "David",
    lastName: "Williams",
    email: "DavidW@gmail.com",
    phone: "0456123789",
    address: "31 Oak Street",
    contractType: "Contract",
    startDate: new Date("2023-07-01"),
    finishDate: new Date("2023-12-31"),
    employmentType: "Part-Time",
    hoursPerWeek: 25.0,
  },
  {
    firstName: "Olivia",
    lastName: "Nguyen",
    email: "OliviaN@yahoo.com",
    phone: "0987456123",
    address: "18 Maple Avenue",
    contractType: "Permanent",
    startDate: new Date("2023-06-15"),
    finishDate: new Date("2024-06-30"),
    employmentType: "Full-Time",
    hoursPerWeek: 40.0,
  },
  {
    firstName: "Daniel",
    lastName: "Kim",
    email: "DanielK@gmail.com",
    phone: "0312457896",
    address: "55 Pine Street",
    contractType: "Contract",
    startDate: new Date("2023-05-01"),
    finishDate: new Date("2023-11-30"),
    employmentType: "Part-Time",
    hoursPerWeek: 30.0,
  },
  {
    firstName: "Sophia",
    lastName: "Brown",
    email: "SophiaB@yahoo.com",
    phone: "0768123456",
    address: "10 Rose Lane",
    contractType: "Contract",
    startDate: new Date("2023-04-15"),
    finishDate: new Date("2024-04-30"),
    employmentType: "Part-Time",
    hoursPerWeek: 25.0,
  },
  {
    firstName: "Ethan",
    lastName: "Hernandez",
    email: "EthanH@gmail.com",
    phone: "0321567890",
    address: "24 Sunflower Street",
    contractType: "Permanent",
    startDate: new Date("2023-03-01"),
    finishDate: new Date("2024-03-31"),
    employmentType: "Full-Time",
    hoursPerWeek: 38.0,
  },
  {
    firstName: "Ava",
    lastName: "Smith",
    email: "AvaS@yahoo.com",
    phone: "0978654321",
    address: "14 Daisy Lane",
    contractType: "Permanent",
    startDate: new Date("2023-02-15"),
    finishDate: new Date("2023-08-31"),
    employmentType: "Full-Time",
    hoursPerWeek: 40.0,
  },
  {
    firstName: "John",
    lastName: "Doe",
    email: "JohnDoe@gmail.com",
    phone: "03266895",
    address: "3 Merrylands Street",
    contractType: "Permanent",
    startDate: new Date("2023-12-13"),
    finishDate: new Date("2024-12-31"),
    employmentType: "Full-Time",
    hoursPerWeek: 38.0,
  },
  {
    firstName: "Sara",
    lastName: "Connor",
    email: "SaraConnor@gmail.com",
    phone: "0475123649",
    address: "27 Albert Road",
    contractType: "Permanent",
    startDate: new Date("2023-12-13"),
    finishDate: new Date("2023-12-31"),
    employmentType: "Full-Time",
    hoursPerWeek: 38.0,
  },
  {
    firstName: "Taylor",
    lastName: "Gomez",
    email: "Tgomez@yahoo.com",
    phone: "0475058205",
    address: "23 Herbert Road",
    contractType: "Contract",
    startDate: new Date("2023-12-13"),
    finishDate: new Date("2023-12-31"),
    employmentType: "Full-Time",
    hoursPerWeek: 38.0,
  },
  {
    firstName: "Andy",
    lastName: "Garcia",
    email: "AndyG@msn.com",
    phone: "0585058406",
    address: "78 Stokes Street",
    contractType: "Contract",
    startDate: new Date("2023-12-13"),
    finishDate: new Date("2023-12-31"),
    employmentType: "Part-Time",
    hoursPerWeek: 25.0,
  },
  {
    firstName: "Cameron",
    lastName: "Diaz",
    email: "CameronD@google.com",
    phone: "0414741569",
    address: "78 Stokes Street",
    contractType: "Contract",
    startDate: new Date("2023-12-13"),
    finishDate: new Date("2023-12-31"),
    employmentType: "Part-Time",
    hoursPerWeek: 25.0,
  },
];
